export { default as Navbar } from './Navbar.vue';
export { default as Footer } from './Footer.vue';
export { default as ScrollView } from './ScrollView.vue';
export { default as Collection } from './Collection.vue';
// export { default as TabsSection } from './TabsSection.vue';
// export { default as TabsWrapper } from './TabsWrapper.vue';
// export { default as Tab } from './Tab.vue';
export { default as Faq } from './Faq.vue';
export { default as Containers } from './Containers.vue';
export { default as Licenses } from './Licenses.vue';
export { default as Social } from './Social.vue';
export { default as Roadmap } from './Roadmap.vue';
export { default as Secured } from './Secured.vue';
export { default as Experience } from './Experience.vue';
export { default as SubscribeModal } from './SubscribeModal.vue';
export { default as Preloader } from './Preloader.vue';
export { default as TeamPattern } from './TeamPattern.vue';
export { default as TeamPage } from './TeamPage.vue';
export { default as TeamAbout } from './TeamAbout.vue';
